### ISSUE TITLE
How can I get TPCx-HS-master_MR*.jar source code?

### ISSUE THREAD

**Issue by oeegee** [valuko/TPCx-HS#1]
Dear Victor Aluko!

How can I get the source code?

TPCx-HS-master_MR1.jar 
TPCx-HS-master_MR2.jar 
TPCx-HS-master_Spark.jar

I'm gonna check some logic.

Thank you~!!

**Comment by valuko** [comment]
Hi Daniel,

I have added the source code for all the jar files into the project. You can check it here: https://github.com/valuko/tpcx_hs/tree/master/TPCx-HS-src-kit/TPCx-HS-SRC
